### PR TITLE
Reentrant lexer: remove FlexLexer.h dependency

### PR DESCRIPTION
**Pull request by tusharpm**
Replace the C++ lexer with the reentrant lexer.
- No dependency on `FlexLexer.h`. Remove reference to `FLEX_INCLUDE_DIRS`.

References:
- [CMake LexerParser](https://github.com/Kitware/CMake/tree/master/Source/LexerParser).
- [Github Linguist](https://github.com/github/linguist/tree/master/ext/linguist).

### CODE REVIEW

**Comment by TheJJ** [comment]
I'm not that keen on committing generated files. What is the problem of using flex? It's available on all distros and works quite stably.

**Comment by tusharpm** [comment]
I was going for removing the `FlexLexer.h` dependency, which is notoriously tricky to manage on Windows due to the lack of a package manager (vcpkg doesn't have flex). That's handled in the first commit.

If having a checked-in lexer is unacceptable: I can revert the second commit, which basically allows removing the `flex` invocation from the build.

**Comment by TheJJ** [comment]
Hm you have a point. Are there other lexers that can be used instead? For the repo sanity, i would really like to avoid committing generated files.

Is packaging flex for vcpkg not possible?

**Comment by tusharpm** [comment]
I went through [this list of lexer generators](https://en.wikipedia.org/wiki/Lexical_analysis#List_of_lexer_generators), it seems like flex is the popular choice. The others I liked are [re2c](http://re2c.org/) and [RE/Flex](https://www.genivia.com/doc/reflex/html/), in decreasing order. (I don't know when I can actually try them.) Note that both have the same problem as flex - missing dependency management for Windows (vcpkg provides neither).
About not committing generated files: I understand the concern. I agree with your decision there.

Packaging flex for vcpkg should technically be possible; but as [it builds using autotools](https://github.com/westes/flex), I guess its "port" would have to supply a downstream `CMakeLists.txt` patch.

**Comment by TheJJ** [comment]
@zuntrax says:
> @tusharpm: nope, win_flex works
FindFlex.cmake checks for both flex.exe and win_flex.exe
just needs to be in the path
that's already set up in our vm

**Comment by ras0219-msft** [comment]
Building with autotools in vcpkg is possible via msys2 (see ffmpeg). However, since flex is consumed primarily as a binary (iirc?) it would also be fine to just download a precompiled copy of `win_flex.exe` and put it into `tools\flex\win_flex.exe`.

**Comment by tusharpm** [comment]
> win_flex works

That's good. I didn't know that. Next, I just need to figure out how to make vcpkg "install" it.

However, the problem still exists for the Cygwin package, an alternative way of acquiring flex. While win_flex has FlexLexer.h in the same directory (which is in PATH and therefore might set `FLEX_INCLUDE_DIRS` properly); Cygwin flex has it in a different directory, which has to be explicitly specified to CMake.
Something similar is observed in #22 for macOS, also.

This change reduces the requirement of the specifying the flex include directory. It doesn't affect the existing installations.

**Comment by TheJJ** [comment]
Any success so far?

**Comment by tusharpm** [comment]
Oh sorry, I didn't know this was waiting for me.
I got `win_flex` working by downloading and extracting win_flex_bison from a URL in the vcpkg repository. It works cleanly as @zuntrax stated.
@ras0219-msft: I did something similar to what you suggested - only, without this change, I'd have to copy `FlexLexer.h` along with `win_flex.exe`. This change removes precisely that requirement.

As I mentioned earlier, this change would be helpful for other ways of installing flex, like Cygwin on Windows or brew/port on macOS, as [the CMake FindFLEX module lacks hints to detect the correct include directory](https://github.com/Kitware/CMake/blob/master/Modules/FindFLEX.cmake#L105-L106).

Briefly, this is a simplification for the first-time build on installing flex through alternate channels.

**Pull request merged**
