### PR TITLE
Detect WindowsStore build environment

### PR DESCRIPTION
**Pull request by heinezen**
This may be enough to build on UWP if someone is daring enough to do this.

@duanqn Can you check if this works before we merge it?

### CODE REVIEW

**Comment by duanqn** [comment]
Sure. I'll confirm it tomorrow.

**Comment by duanqn** [comment]
Looks like the errors are still there.
Can you open the following build logs?
https://dev.azure.com/vcpkg/public/_build/results?buildId=91777&view=logs&j=afe306fb-88a0-5d5e-2934-71aa01507316&t=5029ab74-fefd-5c62-0657-5855530a064d

**Comment by duanqn** [comment]
If it's not easy to fix, I can disable UWP builds for vcpkg as well.

**Comment by heinezen** [comment]
@duanqn I tried again by excluding the problematic code with  compiler flag.

https://learn.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation#universal-windows-platform-uwp

**Comment by heinezen** [comment]
If that doesn't work, then we should disable UWP because I don't know nearly enough about UWP to debug any build problems.

**Comment by duanqn** [comment]
I'm a bit busy these days. I didn't verify your new push, but I think it is probably better to disable UWP builds in vcpkg for now, as we lack the knowledge to maintain it and it could cause extra burden.

**Comment by heinezen** [comment]
@duanqn Agreed. I'll create an issue with our findings later and maybe someone else can pick up on adding UWP builds.

**Comment by duanqn** [comment]
It's probably OK to leave it unsupported for a while, unless we want to build openage as UWP app :).

**Pull request closed without merging**
