### PR TITLE
Update nyan_specification.md

### PR DESCRIPTION
**Pull request by apainintheneck**
A few grammar and spelling updates to improve readability.

### CODE REVIEW

**Review by TheJJ — APPROVED** [review]
thanks for the fixes! :)

(the [iff](https://en.wikipedia.org/wiki/If_and_only_if) is actually math-notation, but we should rather write "when" there to make it more clear)

**Comment by TheJJ** [comment]
If you want, you can update the `iff`-`when` thing, otherwise I'll go ahead and merge!

**Comment by apainintheneck** [comment]
Ah, that totally went over my head. Yeah, I think `when` would be more intuitive there (at least for me).

**Review by TheJJ — APPROVED** [review]
thx!

**Pull request merged**
